In [1]:
from rdkit import Chem
from rdkit.Chem import rdDepictor
from rdkit.Chem import rdDistGeom


smiles = [
    "CN=C=O",
    "CC(=O)NCCC1=CNc2c1cc(OC)cc2",
    "OCCc1c(C)[n+](cs1)Cc2cnc(C)nc2N",
]
mols = [Chem.AddHs(Chem.MolFromSmiles(smi)) for smi in smiles]
for mol in mols:
    rdDepictor.Compute2DCoords(mol)
    rdDistGeom.EmbedMolecule(mol)

In [2]:
from padelpy2 import Calculator, descriptors


calc = Calculator(descriptors)
results = calc(mols)
results

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nAromBond,nAtom,nHeavyAtom,nH,...,P1s,P2s,E1s,E2s,E3s,Ts,As,Vs,Ks,Ds
0,0,-0.8688,0.754813,12.8580,7.422379,0,0,7,4,3,...,0.808381,0.112849,0.577047,0.356790,0.231751,2.666203,1.164328,3.966725,0.712571,1.165587
1,0,-0.7645,0.584460,69.3770,37.352688,0,0,33,17,16,...,0.781462,0.196842,0.524669,0.412909,0.280678,15.848644,43.968823,73.102559,0.672194,1.218255
2,0,-3.8401,14.746368,70.5581,40.557481,0,0,35,18,17,...,0.788617,0.128478,0.485130,0.430483,0.372944,14.607390,37.842570,78.631368,0.682925,1.288556

In [3]:
from padelpy2 import descriptors_2d


calc = Calculator(descriptors_2d)
results = calc(mols)
results

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nAromBond,nAtom,nHeavyAtom,nH,...,AMW,WTPT-1,WTPT-2,WTPT-3,WTPT-4,WTPT-5,WPATH,WPOL,XLogP,Zagreb
0,0,-0.8688,0.754813,12.8580,7.422379,0,0,7,4,3,...,8.145923,6.871320,1.717830,4.871320,2.310660,2.560660,10.0,1.0,1.720,10.0
1,0,-0.7645,0.584460,69.3770,37.352688,0,0,33,17,16,...,7.033975,34.195857,2.011521,11.205410,5.185927,6.019483,561.0,22.0,0.963,84.0
2,0,-3.8401,14.746368,70.5581,40.557481,0,0,35,18,17,...,7.574637,35.963686,1.997983,17.433614,2.437028,11.940324,642.0,25.0,-0.461,90.0

In [4]:
from padelpy2 import descriptors_3d


calc = Calculator(descriptors_3d)
results = calc(mols)
results

,TDB1u,TDB2u,TDB3u,TDB4u,TDB5u,TDB6u,TDB7u,TDB8u,TDB9u,TDB10u,...,P1s,P2s,E1s,E2s,E3s,Ts,As,Vs,Ks,Ds
0,1.216074,2.065688,2.997120,3.793240,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.808381,0.112849,0.577047,0.356790,0.231751,2.666203,1.164328,3.966725,0.712571,1.165587
1,1.253925,2.193232,3.101146,3.953356,4.762385,5.709920,6.778705,7.650312,8.416965,9.673263,...,0.781462,0.196842,0.524669,0.412909,0.280678,15.848644,43.968823,73.102559,0.672194,1.218255
2,1.279595,2.215689,3.138171,4.008065,4.591506,5.342969,6.007745,6.619638,7.727231,8.345799,...,0.788617,0.128478,0.485130,0.430483,0.372944,14.607390,37.842570,78.631368,0.682925,1.288556

In [5]:
from padelpy2 import fingerprints


calc = Calculator(fingerprints)
results = calc(mols)
results

,FP1,FP2,FP3,FP4,FP5,FP6,FP7,FP8,FP9,FP10,...,APC2D10_I_I,APC2D10_I_B,APC2D10_I_Si,APC2D10_I_X,APC2D10_B_B,APC2D10_B_Si,APC2D10_B_X,APC2D10_Si_Si,APC2D10_Si_X,APC2D10_X_X
0,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0,1,0,0,0,0,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
from padelpy2.fingerprints import MACCSFingerprinter


calc = Calculator([MACCSFingerprinter])
results = calc(mols)
results

,MACCSFP1,MACCSFP2,MACCSFP3,MACCSFP4,MACCSFP5,MACCSFP6,MACCSFP7,MACCSFP8,MACCSFP9,MACCSFP10,...,MACCSFP157,MACCSFP158,MACCSFP159,MACCSFP160,MACCSFP161,MACCSFP162,MACCSFP163,MACCSFP164,MACCSFP165,MACCSFP166
0,0,0,0,0,0,0,0,0,0,0,...,0,1,0,1,1,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
2,0,0,0,0,0,0,0,0,0,0,...,1,1,0,1,1,1,1,1,1,0